#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Astro-Catalog
version:      2.1.3
version_from: 
installdirs:  site
requires:
    Pod::Usage:                    1.14
    Net::Domain:                   2.13
    LWP:                           5.53

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
