---
abstract: 'A generic astronomical catalogue class'
author:
  - 'Alasdair Allan E<lt>aa@astro.ex.ac.ukE<gt>,'
  - 'Tim Jenness E<lt>tjenness@cpan.orgE<gt>'
  - 'Tim Lister E<lt>tlister@lcogt.netE<gt>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.3
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Astro-Catalog
provides:
  Astro::Catalog:
    file: lib/Astro/Catalog.pm
    version: 2.02
  Astro::Catalog::IO::ASCII:
    file: lib/Astro/Catalog/IO/ASCII.pm
    version: 0.03
  Astro::Catalog::IO::ASSM:
    file: lib/Astro/Catalog/IO/ASSM.pm
    version: 0.02
  Astro::Catalog::IO::Astrom:
    file: lib/Astro/Catalog/IO/Astrom.pm
    version: 0.01
  Astro::Catalog::IO::Binary:
    file: lib/Astro/Catalog/IO/Binary.pm
    version: 0.01
  Astro::Catalog::IO::Cluster:
    file: lib/Astro/Catalog/IO/Cluster.pm
    version: 2.01
  Astro::Catalog::IO::FINDOFF:
    file: lib/Astro/Catalog/IO/FINDOFF.pm
    version: 0.01
  Astro::Catalog::IO::FITSTable:
    file: lib/Astro/Catalog/IO/FITSTable.pm
    version: 0.01
  Astro::Catalog::IO::GaiaPick:
    file: lib/Astro/Catalog/IO/GaiaPick.pm
    version: 0.01
  Astro::Catalog::IO::JCMT:
    file: lib/Astro/Catalog/IO/JCMT.pm
    version: 0.16
  Astro::Catalog::IO::LCOGTFITSTable:
    file: lib/Astro/Catalog/IO/LCOGTFITSTable.pm
    version: 0.05
  Astro::Catalog::IO::Northstar:
    file: lib/Astro/Catalog/IO/Northstar.pm
    version: 0.01
  Astro::Catalog::IO::RITMatch:
    file: lib/Astro/Catalog/IO/RITMatch.pm
    version: 0.01
  Astro::Catalog::IO::SExtractor:
    file: lib/Astro/Catalog/IO/SExtractor.pm
    version: 0.01
  Astro::Catalog::IO::STL:
    file: lib/Astro/Catalog/IO/STL.pm
    version: 0.01
  Astro::Catalog::IO::Simple:
    file: lib/Astro/Catalog/IO/Simple.pm
    version: 2.00
  Astro::Catalog::IO::TST:
    file: lib/Astro/Catalog/IO/TST.pm
    version: 0.03
  Astro::Catalog::IO::UKIRTBS:
    file: lib/Astro/Catalog/IO/UKIRTBS.pm
    version: 0.01
  Astro::Catalog::IO::VOTable:
    file: lib/Astro/Catalog/IO/VOTable.pm
    version: 2.00
  Astro::Catalog::IO::XY:
    file: lib/Astro/Catalog/IO/XY.pm
    version: 0.01
  Astro::Catalog::Item:
    file: lib/Astro/Catalog/Item.pm
    version: 2.00
  Astro::Catalog::Item::Morphology:
    file: lib/Astro/Catalog/Item/Morphology.pm
    version: 2.00
  Astro::Catalog::Query:
    file: lib/Astro/Catalog/Query.pm
    version: 2.00
  Astro::Catalog::Query::2MASS:
    file: lib/Astro/Catalog/Query/2MASS.pm
    version: 2.00
  Astro::Catalog::Query::CMC:
    file: lib/Astro/Catalog/Query/CMC.pm
    version: 2.00
  Astro::Catalog::Query::GSC:
    file: lib/Astro/Catalog/Query/GSC.pm
    version: 2.00
  Astro::Catalog::Query::MPC:
    file: lib/Astro/Catalog/Query/MPC.pm
    version: 2.00
  Astro::Catalog::Query::SIMBAD:
    file: lib/Astro/Catalog/Query/SIMBAD.pm
    version: 0.01
  Astro::Catalog::Query::Sesame:
    file: lib/Astro/Catalog/Query/Sesame.pm
    version: 2.00
  Astro::Catalog::Query::SkyCat:
    file: lib/Astro/Catalog/Query/SkyCat.pm
    version: 0.02
  Astro::Catalog::Query::SuperCOSMOS:
    file: lib/Astro/Catalog/Query/SuperCOSMOS.pm
    version: 2.00
  Astro::Catalog::Query::USNOA2:
    file: lib/Astro/Catalog/Query/USNOA2.pm
    version: 2.00
  Astro::Catalog::Query::Vizier:
    file: lib/Astro/Catalog/Query/Vizier.pm
    version: 2.00
  Astro::Catalog::Star:
    file: lib/Astro/Catalog/Star.pm
    version: 2.00
  Astro::Catalog::Star::Morphology:
    file: lib/Astro/Catalog/Star/Morphology.pm
    version: 2.00
  Astro::Catalog::Transport::REST:
    file: lib/Astro/Catalog/Transport/REST.pm
    version: 2.00
  Astro::Catalog::Transport::WebService:
    file: lib/Astro/Catalog/Transport/WebService.pm
    version: 2.00
  Tk::AstroCatalog:
    file: lib/Tk/AstroCatalog.pm
    version: 0.14
recommends:
  Astro::FITS::CFITSIO: 1.03
  Astro::VO::VOTable: 0.9
  Tk: 804.029
requires:
  Astro::Coords: 0.12
  Astro::Flux: 0.01
  Astro::Telescope: 0.5
  Carp: 1.01
  Class::Struct: 0.63
  Data::Dumper: 2.12
  DateTime: 0
  DateTime::Format::ISO8601: 0
  File::Spec: 0.84
  File::Temp: 0.14
  LWP: 5.53
  Misc::Quality: 0.01
  Net::Domain: 2.13
  Number::Uncertainty: 0.01
  Pod::Usage: 1.14
  SOAP::Lite: 0
  Scalar::Util: 1.14
  Time::Piece: 1.08
resources:
  homepage: http://github.com/timj/perl-Astro-Catalog/tree/master
  license: http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
  repository: git://github.com/timj/perl-Astro-Catalog.git
version: 4.27
